spring:
  datasource:
    url: jdbc:mysql://localhost:3306/legeno_around_here
    username: root
    password: ittabi
    data: classpath:initial_data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
security:
  jwt:
    token:
      secret-key: hihirachsecretkey
      expire_length: 3600000
