spring:
  datasource:
    url: jdbc:mysql://localhost:3306/legeno-around-here
    username: ittabi
    password: ittabi
  jpa:
    hibernate:
      ddl-auto: create
security:
  jwt:
    token:
      secret-key: hihirachsecretkey
      expire_length: 3600000
